### ISSUE TITLE
Compile to minified CSS?

### ISSUE THREAD

**Issue by getsetbro** [JustinBeckwith/OrangeBits#1]
Thank you for this, I was happy to see a LESS compiler in the extensions for WebMatrix. 
Would you consider adding the option for the output CSS to be minified? Sans comments, whitespace, and extra characters. I would use LESS.app but it is for MAC OS X only.

**Comment by JustinBeckwith** [comment]
Glad it's working out well for you!  I have a minify command working, the only part left is getting it to automatically run for a given file / directory.  If I do it this way, compiling less would generate {filename}.css, which would automatically get minified into {filename}.min.css.  This should be coming soon.

**Comment by JustinBeckwith** [comment]
This is in the latest release - you can set up auto-minification in the options
