### ISSUE TITLE
Provide a way to get compiler output

### ISSUE THREAD

**Issue by JustinBeckwith** [JustinBeckwith/OrangeBits#11]
When compilation fails, the output currently isn't available in a log window or in the copy details.  There needs to be an easy way to get the output.

**Comment by mitchell360** [comment]
Minimum viable version of this feature would just be a LESS compilation log in a known location.

Evolve the feature to make the information more visible in the WebMatrix UI.

**Comment by kahlusha** [comment]
Any thoughts on this? Is the project dead?

**Comment by mitchelldemler** [comment]
Project must be dead... Issue is nearly a year old and no resolution. It's difficult to debug LESS with no compilation error log.

**Comment by JustinBeckwith** [comment]
Added support for this in a9b874ca10fb994d3aa0aaeb7a7edddf9dfe195d.  It now will show the output in the logs tab at the bottom.
