### ISSUE TITLE
No autocompletion for SCSS

### ISSUE THREAD

**Issue by jgclifton** [JustinBeckwith/OrangeBits#13]
Is this supposed to autocomplete for SCSS? Webmatrix is working just fine with CSS but using this extension there's no autocompletion for SCSS.

**Comment by JustinBeckwith** [comment]
This extension only provides the compilation of SCSS files - the colorization and auto-complete is built into the editor for ones that we support.  Currently we don't have SCSS IntelliSense support, but you can vote on it in our UserVoice forum:

http://webmatrix.uservoice.com/forums/128313-webmatrix-suggestions/suggestions/3183980-fully-support-scss-sassy-sass-
