### ISSUE TITLE
Auto-compile won't turn off (.scss)

### ISSUE THREAD

**Issue by kahlusha** [JustinBeckwith/OrangeBits#14]
New to OrangeBits, so maybe I'm missing something here.

I've right-clicked my child .scss files and unchecked all the 'auto-compile' boxes, yet everytime I save the .scss file, a .css file is created. Of course, there isn't a checkbox for "scss", only less, css, and coffeescript, so perhaps that's the issue.

I'm importing these to my main .scss file, so I don't need them compiled separately.  If it's a scss support issue, I hope to see scss supported in the next release.

**Comment by jgclifton** [comment]
Unfortunately this project seems to be dead - I asked something a week ago that remains unanswered.

**Comment by kahlusha** [comment]
That's sad.  Just made the switch to WebMatrix and thought this was an awesome plugin.  Back to running Compass, then.

**Comment by JustinBeckwith** [comment]
I'm still active, just busy :)  I can take a look at this tonight.

**Comment by JustinBeckwith** [comment]
Fixed in OrangeBits 1.0.7

**Comment by kahlusha** [comment]
Yay. Thanks.
