### ISSUE TITLE
Is their any way to stop compilation notifcation in bottom of webmatrix ?

### ISSUE THREAD

**Issue by ghost** [JustinBeckwith/OrangeBits#4]
Webmatrix itself not auto-hide the notification nor I found any setting that make me able to disable these notification.

Is their any way to stop this kind of notification in webmatrix which is generated by orangebit because of less file compilation.

reference :
http://webmatrix.uservoice.com/forums/128313-webmatrix-suggestions/suggestions/2974893-is-their-any-way-to-stop-notification-to-appear-ev

**Comment by JustinBeckwith** [comment]
Yeah - I've gotten enough complaints about that :-)  I'm removing the notification for successful actions, and I should have a new build for you this week.  I'll let you know!

**Comment by JustinBeckwith** [comment]
Removed the notification - eventually adding it to the console output
