### ISSUE TITLE
Set path of the compiled files

### ISSUE THREAD

**Issue by garthenweb** [JustinBeckwith/OrangeBits#6]
I did not found a solution to set the build path of the file i like to compile.
I e.g. like to have a folder assets/less with my less-files and want to compile them to assets/css.

Is this already possible?

**Comment by JustinBeckwith** [comment]
This isn't currently possible - but I'm willing to add it.  Should have something in the next week for you!

**Comment by JustinBeckwith** [comment]
Added this in the latest release - update the extension, and check out right click -> OrangeBits options
