### ISSUE TITLE
Option to remove automatically generated code comments

### ISSUE THREAD

**Issue by itsnydell** [JustinBeckwith/OrangeBits#9]
I would be great to have an option to included less information in the automatically generated code comment.

I would like the option to remove the following from the automatically generated comment:
- Compiled by: _____________
- Source: _________________

Or maybe an option to select what you would like to include in that comment. 

It would be very helpful for those of us who compile allot and use the compiled code directly on our websites. Some of the information in those two lines are not for public eye. I know it's easy enough to go and edit the css file but that becomes a pain when our css is compiled many times and pushed to our website right away.

**Comment by JustinBeckwith** [comment]
I've been thinking about just having a single line comment at the top with the auto-compile message and a time stamp.  Would that be better?

**Comment by itsnydell** [comment]
I think that would work perfect. Just enough information to be useful and not too much that private information is added to the comment.

**Comment by mitchell360** [comment]
Let me preface this with saying that I understand where @itsnydell is coming from. However, I would recommend that this OrangeBits branding only get removed in the .min versions.

Anyone using a free and open source tool such as OrangeBits should be fine with those comments at the top.  Virtually every open source product leaves some artifact in the code (think JQuery, bootstrap, etc.).

I think that it is a good way for the WebMatrix and OrangeBits team to get credit for the great work. Gotta throw everyone who labors for free SOME sort of bone. Right?

**Comment by JustinBeckwith** [comment]
Thanks folks.  Someone asked to have the comments in a previous issue, so there it is :)  It's not there as a sales pitch, rather as a way to let folks know that the file is auto-generated.  Otherwise you may start making edits without realizing they will be overridden.  Honestly, you should probably be minifying the source anyhow.  I'd rather not add another feature just for this.
